version: "3.8"
services:
  web:
    image: nginx:1.20.1-alpine
    ports:
      - 80:80
    volumes:
      - ./public:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  app:
    build: ./docker/php
    volumes:
      - ./public:/work
